### ISSUE TITLE
Missing Barometer Gauge 

### ISSUE THREAD

**Issue by OlsBean** [lrosenman/WS1001-Template#2]
The Barometer Gauge  was not being drawn because trend.json and temptrend.json were not being populated with livedata as stationcron.php and chartcron.php were trying to load the datafile from /cronfiles/ and not the parent directory. I'm not sure if this is due to my local setup (Windows/IIS10) but the fix I used was to change;

`$json = file_get_contents($livedata);`

to

`$json = file_get_contents('../'.$livedata);`

in both 

stationcron.php and chartcron.php

**Comment by lrosenman** [comment]
we solved this over on WXForum.net.  The weatherdata/weatherstation/updateweatherstation.php file does all the translation.
